version: '3.8'
name: 'git-action'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - "db"
    networks:
      - networkName

  db:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - networkName
    
networks:
  networkName:
    driver: bridge

volumes:
  postgres-data:

