name: Docker Image CI

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "homolog" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest tests
        run: yarn test

      - name: Build the app
        run: yarn build

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{vars.DOCKER_HUB_REPO}}:${{github.sha}}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{vars.DOCKER_HUB_REPO}}:${{github.sha}}
